In [670]:
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [671]:
data =load_breast_cancer()

In [672]:
data

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry \n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        largest values) of these features were computed for each image,\n        resulting in 30 features.  For

In [673]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [674]:
print(data['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [675]:
print(data["data"])

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [676]:
data["data"].shape

(569, 30)

In [677]:
data["feature_names"]
#30 attributes of data

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [678]:
data["data"][0]
#30 attribute value of 1st instantance

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [679]:
# all value of attribute for 1st instance
j=0
for i in data["feature_names"]:
  print(i,":",data["data"][568][j])
  j+=1

mean radius : 7.76
mean texture : 24.54
mean perimeter : 47.92
mean area : 181.0
mean smoothness : 0.05263
mean compactness : 0.04362
mean concavity : 0.0
mean concave points : 0.0
mean symmetry : 0.1587
mean fractal dimension : 0.05884
radius error : 0.3857
texture error : 1.428
perimeter error : 2.548
area error : 19.15
smoothness error : 0.007189
compactness error : 0.00466
concavity error : 0.0
concave points error : 0.0
symmetry error : 0.02676
fractal dimension error : 0.002783
worst radius : 9.456
worst texture : 30.37
worst perimeter : 59.16
worst area : 268.6
worst smoothness : 0.08996
worst compactness : 0.06444
worst concavity : 0.0
worst concave points : 0.0
worst symmetry : 0.2871
worst fractal dimension : 0.07039


In [680]:
data["target_names"]

array(['malignant', 'benign'], dtype='<U9')

In [681]:
feature=data["data"]

In [682]:
label=data["target"]
#for malignant =1
#for benign =0

In [683]:
data["target"].shape

(569,)

In [684]:
data["target_names"]

array(['malignant', 'benign'], dtype='<U9')

In [685]:
feature

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [686]:
feature.shape

(569, 30)

In [687]:
label.shape

(569,)

In [688]:
scale = StandardScaler()

feature = scale.fit_transform(feature)

In [689]:
j=0
for i in data["feature_names"]:
  print(i,":",feature[0][j])
  j+=1

mean radius : 1.0970639814699807
mean texture : -2.0733350146975935
mean perimeter : 1.2699336881399383
mean area : 0.9843749048031144
mean smoothness : 1.568466329243428
mean compactness : 3.2835146709868264
mean concavity : 2.652873983743168
mean concave points : 2.532475216403245
mean symmetry : 2.2175150059646405
mean fractal dimension : 2.255746885296269
radius error : 2.4897339267376193
texture error : -0.5652650590684639
perimeter error : 2.833030865855184
area error : 2.4875775569611043
smoothness error : -0.21400164666895383
compactness error : 1.3168615683959484
concavity error : 0.72402615808036
concave points error : 0.6608199414286064
symmetry error : 1.1487566671861758
fractal dimension error : 0.9070830809973359
worst radius : 1.8866896251792757
worst texture : -1.3592934737640827
worst perimeter : 2.3036006236225606
worst area : 2.0012374893299207
worst smoothness : 1.3076862710715387
worst compactness : 2.616665023512603
worst concavity : 2.1095263465722556
worst conca

In [690]:
print(feature[19])
print(data["target_names"][label[19]],label[19])

[-0.16679919 -1.1471623  -0.18572799 -0.2519565   0.10174657 -0.43685025
 -0.27820957 -0.02860929  0.26791123 -0.72830966 -0.48822526 -0.77699899
 -0.40001405 -0.36912442  0.4736929  -0.60797417 -0.26604255  0.21960965
 -0.08987642 -0.56544939 -0.24004796 -1.04500496 -0.22521706 -0.29776075
  0.50987305 -0.48960521 -0.15922253  0.21612292  0.12334653 -0.62929189]
benign 1


In [691]:
df=pd.DataFrame(feature, columns=data["feature_names"])

In [692]:
df

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0       1.097064     -2.073335  ...        2.750622                 1.937015
1       1.829821     -0.353632  ...       -0.243890                 0.281190
2       1.579888      0.456187  ...        1.152255                 0.201391
3      -0.768909      0.253732  ...        6.046041                 4.935010
4       1.750297     -1.151816  ...       -0.868353                -0.397100
..           ...           ...  ...             ...                      ...
564     2.110995      0.721473  ...       -1.360158                -0.709091
565     1.704854      2.085134  ...       -0.531855                -0.973978
566     0.702284      2.045574  ...       -1.104549                -0.318409
567     1.838341      2.336457  ...        1.919083                 2.219635
568    -1.808401      1.221792  ...       -0.048138                -0.751207

[569 rows x 30 columns]

In [693]:
#400 training data
x_train=feature[:400]
y_train=label[:400]

#85 validation data
x_val=feature[400:485]
y_val=label[400:485]

#84 test data
x_test=feature[485:569]
y_test=label[485:569]

In [694]:
#creation of neural network
model = Sequential()
#hidden layer
model.add(Dense(64, activation = 'relu', input_dim = 30))
model.add(Dense(16, activation = 'relu'))
model.add(Dense(4, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

In [695]:
model.compile( loss = 'binary_crossentropy' , optimizer = 'adam' , metrics = ['accuracy'])

In [701]:
model.fit( x_train , y_train, epochs = 10, batch_size = 5, validation_data = (x_val, y_val))

Epoch 1/10
80/80 [==============================] - 0s 2ms/step - loss: 0.0791 - accuracy: 1.0000 - val_loss: 0.0830 - val_accuracy: 0.9647
Epoch 2/10
80/80 [==============================] - 0s 2ms/step - loss: 0.0751 - accuracy: 1.0000 - val_loss: 0.0510 - val_accuracy: 0.9882
Epoch 3/10
80/80 [==============================] - 0s 2ms/step - loss: 0.0722 - accuracy: 1.0000 - val_loss: 0.0512 - val_accuracy: 1.0000
Epoch 4/10
80/80 [==============================] - 0s 2ms/step - loss: 0.0690 - accuracy: 1.0000 - val_loss: 0.0479 - val_accuracy: 1.0000
Epoch 5/10
80/80 [==============================] - 0s 2ms/step - loss: 0.0661 - accuracy: 1.0000 - val_loss: 0.0417 - val_accuracy: 1.0000
Epoch 6/10
80/80 [==============================] - 0s 2ms/step - loss: 0.0640 - accuracy: 1.0000 - val_loss: 0.0483 - val_accuracy: 1.0000
Epoch 7/10
80/80 [==============================] - 0s 2ms/step - loss: 0.0611 - accuracy: 1.0000 - val_loss: 0.0441 - val_accuracy: 1.0000
Epoch 8/10
80/80 [==

In [702]:
model.evaluate(x_test , y_test)

3/3 [==============================] - 0s 3ms/step - loss: 0.0929 - accuracy: 0.9762


[0.09288307279348373, 0.976190447807312]

In [698]:
for i in range(30):
  sample = x_test[i]
  sample = np.reshape(sample, (1,30))
  
  if (model.predict(sample)[0][0] > 0.5):
    print("-Benign")
  else:
    print("-Malignant")

  if (y_test[i] == 1):
    print("*Banign")
  else:
    print("*Melignant")
  print("-----------")

-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Malignant
*Melignant
-----------
-Benign
*Banign
-----------
-Benign
*Melignant
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Malignant
*Melignant
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Malignant
*Melignant
-----------
-Malignant
*Melignant
-----------
-Benign
*Banign
-----------
-Malignant
*Melignant
-----------
-Benign
*Banign
-----------
-Malignant
*Melignant
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Malignant
*Melignant
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Malignant
*Melignant
-----------
-Benign
*Banign
-----------
-Malignant
*Melignant
-----------
